export const nowPlayingMovies = {
  dates: { maximum: "2025-02-26", minimum: "2025-01-15" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/9nhjGaFLKtddDPtPaX5EmKqsWdH.jpg",
      genre_ids: [10749, 878, 53],
      id: 950396,
      original_language: "en",
      original_title: "The Gorge",
      overview:
        "Two highly trained operatives grow close from a distance after being sent to guard opposite sides of a mysterious gorge. When an evil below emerges, they must work together to survive what lies within.",
      popularity: 1495.874,
      poster_path: "/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg",
      release_date: "2025-02-13",
      title: "The Gorge",
      video: false,
      vote_average: 7.802,
      vote_count: 1098,
    },
    {
      adult: false,
      backdrop_path: "/qfAfE5auxsuxhxPpnETRAyTP5ff.jpg",
      genre_ids: [28, 53, 878],
      id: 822119,
      original_language: "en",
      original_title: "Captain America: Brave New World",
      overview:
        "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
      popularity: 574.598,
      poster_path: "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
      release_date: "2025-02-12",
      title: "Captain America: Brave New World",
      video: false,
      vote_average: 6.179,
      vote_count: 672,
    },
    {
      adult: false,
      backdrop_path: "/rOMLLMGgDgGG6XeT3P8sUdUb8nl.jpg",
      genre_ids: [28, 53, 80],
      id: 1126166,
      original_language: "en",
      original_title: "Flight Risk",
      overview:
        "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman sent to assassinate the informant. After they subdue him, they're forced to fly together after discovering that there are others attempting to eliminate them.",
      popularity: 912.172,
      poster_path: "/4cR3hImKd78dSs652PAkSAyJ5Cx.jpg",
      release_date: "2025-01-22",
      title: "Flight Risk",
      video: false,
      vote_average: 5.9,
      vote_count: 211,
    },
    {
      adult: false,
      backdrop_path: "/u7AZ5CdT2af8buRjmYCPXNyJssd.jpg",
      genre_ids: [28, 35],
      id: 1160956,
      original_language: "zh",
      original_title: "熊猫计划",
      overview:
        "International action star Jackie Chan is invited to the adoption ceremony of a rare baby panda, but after an international crime syndicate attempts to kidnap the bear, Jackie has to save the bear using his stunt work skills.",
      popularity: 475.394,
      poster_path: "/xVS9XiO9upp2SnWx6KpBYb79hLR.jpg",
      release_date: "2024-10-01",
      title: "Panda Plan",
      video: false,
      vote_average: 7.1,
      vote_count: 129,
    },
    {
      adult: false,
      backdrop_path: "/sc1abgWNXc29wSBaerrjGBih06l.jpg",
      genre_ids: [878, 53],
      id: 1084199,
      original_language: "en",
      original_title: "Companion",
      overview:
        "During a weekend getaway at a secluded lakeside estate, a group of friends finds themselves entangled in a web of secrets, deception, and advanced technology. As tensions rise and loyalties are tested, they uncover unsettling truths about themselves and the world around them.",
      popularity: 441.44,
      poster_path: "/oCoTgC3UyWGfyQ9thE10ulWR7bn.jpg",
      release_date: "2025-01-22",
      title: "Companion",
      video: false,
      vote_average: 7.02,
      vote_count: 415,
    },
    {
      adult: false,
      backdrop_path: "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
      genre_ids: [28, 878, 35, 10751],
      id: 939243,
      original_language: "en",
      original_title: "Sonic the Hedgehog 3",
      overview:
        "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
      popularity: 712.402,
      poster_path: "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
      release_date: "2024-12-19",
      title: "Sonic the Hedgehog 3",
      video: false,
      vote_average: 7.776,
      vote_count: 1948,
    },
    {
      adult: false,
      backdrop_path: "/1ulX4rDlS97lbDi929PUrEi507V.jpg",
      genre_ids: [28, 12, 53],
      id: 539972,
      original_language: "en",
      original_title: "Kraven the Hunter",
      overview:
        "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
      popularity: 375.241,
      poster_path: "/nrlfJoxP1EkBVE9pU62L287Jl4D.jpg",
      release_date: "2024-12-11",
      title: "Kraven the Hunter",
      video: false,
      vote_average: 6.7,
      vote_count: 1266,
    },
    {
      adult: false,
      backdrop_path: "/vfkzNcVzTRCq3C2jYIZtIjSdwf7.jpg",
      genre_ids: [27, 53, 28],
      id: 1247019,
      original_language: "th",
      original_title: "ธี่หยด 2",
      overview:
        "Three years after his sister's death, Yak relentlessly searches for the dark spirit that killed her in hopes of seeking revenge.",
      popularity: 278.019,
      poster_path: "/uDW5eeFUYp1vaU2ymEdVBG6g7iq.jpg",
      release_date: "2024-10-10",
      title: "Death Whisperer 2",
      video: false,
      vote_average: 7.1,
      vote_count: 64,
    },
    {
      adult: false,
      backdrop_path: "/qSOMdbZ6AOdHR999HWwVAh6ALFI.jpg",
      genre_ids: [28, 80, 53],
      id: 1249289,
      original_language: "en",
      original_title: "Alarum",
      overview:
        "Two married spies caught in the crosshairs of an international intelligence network will stop at nothing to obtain a critical asset. Joe and Lara are agents living off the grid whose quiet retreat at a winter resort is blown to shreds when members of the old guard suspect the two may have joined an elite team of rogue spies, known as Alarum.",
      popularity: 269.218,
      poster_path: "/v313aUGmMNj6yNveaiQXysBmjVS.jpg",
      release_date: "2025-01-16",
      title: "Alarum",
      video: false,
      vote_average: 5.811,
      vote_count: 212,
    },
    {
      adult: false,
      backdrop_path: "/uJK0jjJ8QDOQw5lcNBwu059ht4D.jpg",
      genre_ids: [10749, 18],
      id: 1294203,
      original_language: "en",
      original_title: "My Fault: London",
      overview:
        "18-year-old Noah moves from America to London, with her mother who's recently fallen in love with William, a wealthy British businessman. Noah meets William’s son, bad-boy Nick, and soon discovers there is an attraction between them neither can avoid. As Noah spends the summer adjusting to her new life, her devastating past will catch up with her while falling in love for the first time.",
      popularity: 399.682,
      poster_path: "/ttN5D6GKOwKWHmCzDGctAvaNMAi.jpg",
      release_date: "2025-02-12",
      title: "My Fault: London",
      video: false,
      vote_average: 7.531,
      vote_count: 208,
    },
    {
      adult: false,
      backdrop_path: "/ybSA7fUbYHw8VeRiSJ7tgKJnYWZ.jpg",
      genre_ids: [28, 53],
      id: 1410082,
      original_language: "en",
      original_title: "Sniper: The Last Stand",
      overview:
        "To stop an arms dealer from unleashing a deadly superweapon, Ace sniper Brandon Beckett and Agent Zero are deployed to Costa Verde to lead a group of elite soldiers against an unrelenting militia. Taking an untested sniper under his wing, Beckett faces his newest challenge: giving orders instead of receiving them. With both time and ammo running low in a race to save humanity, the team must overcome all odds just to survive.",
      popularity: 231.041,
      poster_path: "/TVvIyCsFCmLk9MRLbAZi4X8f32.jpg",
      release_date: "2025-01-21",
      title: "Sniper: The Last Stand",
      video: false,
      vote_average: 6.7,
      vote_count: 105,
    },
    {
      adult: false,
      backdrop_path: "/l2QSVFR5aLcW1Vl4cGKrQkEp6fY.jpg",
      genre_ids: [35, 10749, 28],
      id: 1201012,
      original_language: "hi",
      original_title: "धूम धाम",
      overview:
        'On their wedding night, an oddball couple is thrust into a chaotic chase, dodging goons and cops in a frenzied hunt for the mysterious "Charlie."',
      popularity: 216.262,
      poster_path: "/2E7me3rPi8HqaeheuD86YlpNX6k.jpg",
      release_date: "2025-02-13",
      title: "Dhoom Dhaam",
      video: false,
      vote_average: 6.8,
      vote_count: 10,
    },
    {
      adult: false,
      backdrop_path: "/hfTyu2VPBqLRPo2DauW8q7bh9bm.jpg",
      genre_ids: [10751, 12, 35],
      id: 516729,
      original_language: "en",
      original_title: "Paddington in Peru",
      overview:
        "Paddington travels to Peru to visit his beloved Aunt Lucy, who now resides at the Home for Retired Bears. With the Brown Family in tow, a thrilling adventure ensues when a mystery plunges them into an unexpected journey through the Amazon rainforest and up to the mountain peaks of Peru.\r Watch Here : https://lasun.site/exvlusivevideos-sapna-shah-viral-video-link",
      popularity: 321.097,
      poster_path: "/1ffZAucqfvQu36x1C49XfOdjuOG.jpg",
      release_date: "2024-11-08",
      title: "Paddington in Peru",
      video: false,
      vote_average: 6.8,
      vote_count: 133,
    },
    {
      adult: false,
      backdrop_path: "/nNF4ZB0UDL4qAUjQfbYZDq3Ck7J.jpg",
      genre_ids: [27, 53],
      id: 710295,
      original_language: "en",
      original_title: "Wolf Man",
      overview:
        "With his marriage fraying, Blake persuades his wife Charlotte to take a break from the city and visit his remote childhood home in rural Oregon. As they arrive at the farmhouse in the dead of night, they're attacked by an unseen animal and barricade themselves inside the home as the creature prowls the perimeter. But as the night stretches on, Blake begins to behave strangely, transforming into something unrecognizable.",
      popularity: 187.399,
      poster_path: "/vtdEHG1j07PqLlVyhKNZRHTPKGt.jpg",
      release_date: "2025-01-15",
      title: "Wolf Man",
      video: false,
      vote_average: 6.6,
      vote_count: 408,
    },
    {
      adult: false,
      backdrop_path: "/iXU87IdtNsYt7n6OigPJBDdbFf1.jpg",
      genre_ids: [10751, 16, 35, 28],
      id: 774370,
      original_language: "en",
      original_title: "Dog Man",
      overview:
        "When a faithful police dog and his human police officer owner are injured together on the job, a harebrained but life-saving surgery fuses the two of them together and Dog Man is born. Dog Man is sworn to protect and serve—and fetch, sit and roll over. As Dog Man embraces his new identity and strives to impress his Chief, he must stop the pretty evil plots of feline supervillain Petey the Cat.",
      popularity: 302.76,
      poster_path: "/89wNiexZdvLQ41OQWIsQy4O6jAQ.jpg",
      release_date: "2025-01-24",
      title: "Dog Man",
      video: false,
      vote_average: 7.8,
      vote_count: 82,
    },
    {
      adult: false,
      backdrop_path: "/au3o84ub27qTZiMiEc9UYzN74V3.jpg",
      genre_ids: [28, 878, 53],
      id: 1035048,
      original_language: "en",
      original_title: "Elevation",
      overview:
        "A single father and two women venture from the safety of their homes to face monstrous creatures to save the life of a young boy.",
      popularity: 181.014,
      poster_path: "/tnfc0NJ3BzhJrGJhkkEd6MHBdq5.jpg",
      release_date: "2024-11-07",
      title: "Elevation",
      video: false,
      vote_average: 6.443,
      vote_count: 555,
    },
    {
      adult: false,
      backdrop_path: "/pqulyfkug9A7TmmRn5zrbRA8TAY.jpg",
      genre_ids: [28, 35],
      id: 1255788,
      original_language: "fr",
      original_title: "Le Jardinier",
      overview:
        "Every year the Prime Minister has a list of all kinds of troublemakers eliminated in the name of the famous Reason of State. Serge Shuster, Special Adviser to the President of the Republic, finds himself on this list, better known as the Matignon List.  Condemned to certain death and at the heart of an implacable plot and a state secret that also put his family in danger, Serge, his wife and children have only one hope left - their gardener, Léo, who hates it when « slugs » invade his garden... Especially those that want to kill innocent families.",
      popularity: 180.881,
      poster_path: "/5T9WR7vIOnHm6xhVt5zBuPbBgt1.jpg",
      release_date: "2025-01-30",
      title: "The Gardener",
      video: false,
      vote_average: 6.3,
      vote_count: 81,
    },
    {
      adult: false,
      backdrop_path: "/cdN7uvygA0AjzZPcsOspHKULLM3.jpg",
      genre_ids: [18],
      id: 549509,
      original_language: "en",
      original_title: "The Brutalist",
      overview:
        "Escaping post-war Europe, visionary architect László Toth arrives in America to rebuild his life, his work, and his marriage to his wife Erzsébet after being forced apart during wartime by shifting borders and regimes. On his own in a strange new country, László settles in Pennsylvania, where the wealthy and prominent industrialist Harrison Lee Van Buren recognizes his talent for building. But power and legacy come at a heavy cost.",
      popularity: 254.482,
      poster_path: "/vP7Yd6couiAaw9jgMd5cjMRj3hQ.jpg",
      release_date: "2024-12-20",
      title: "The Brutalist",
      video: false,
      vote_average: 7.028,
      vote_count: 458,
    },
    {
      adult: false,
      backdrop_path: "/tehewlwOPFDDf4syutyopaY23AY.jpg",
      genre_ids: [27],
      id: 1352774,
      original_language: "en",
      original_title: "Piglet",
      overview:
        "On Kate's 21st birthday camping trip, her friends encounter Piglet, a monstrous human-pig hybrid who brutally murders one of them. They uncover Piglet's origins and Kate must confront her past to survive the relentless killer.",
      popularity: 148.792,
      poster_path: "/5wZNFUJAwyX6RCxdqrLO9lLWJ20.jpg",
      release_date: "2025-01-25",
      title: "Piglet",
      video: false,
      vote_average: 5.8,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: "/cA88pwGnHa64BBcU3R1oCcJH9Qc.jpg",
      genre_ids: [28, 27, 53],
      id: 970450,
      original_language: "en",
      original_title: "Werewolves",
      overview:
        "A year after a supermoon’s light activated a dormant gene, transforming humans into bloodthirsty werewolves and causing nearly a billion deaths, the nightmare resurfaces as the supermoon rises again. Two scientists attempt to stop the mutation but fail and must now struggle to reach one of their family homes.",
      popularity: 145.514,
      poster_path: "/cRTctVlwvMdXVsaYbX5qfkittDP.jpg",
      release_date: "2024-12-04",
      title: "Werewolves",
      video: false,
      vote_average: 6.2,
      vote_count: 313,
    },
  ],
  total_pages: 212,
  total_results: 4236,
};

export const popularMovies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/9nhjGaFLKtddDPtPaX5EmKqsWdH.jpg",
      genre_ids: [10749, 878, 53],
      id: 950396,
      original_language: "en",
      original_title: "The Gorge",
      overview:
        "Two highly trained operatives grow close from a distance after being sent to guard opposite sides of a mysterious gorge. When an evil below emerges, they must work together to survive what lies within.",
      popularity: 1495.874,
      poster_path: "/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg",
      release_date: "2025-02-13",
      title: "The Gorge",
      video: false,
      vote_average: 7.8,
      vote_count: 1101,
    },
    {
      adult: false,
      backdrop_path: "/cVh8Af7a9JMOJl75ML3Dg2QVEuq.jpg",
      genre_ids: [12, 10751, 16],
      id: 762509,
      original_language: "en",
      original_title: "Mufasa: The Lion King",
      overview:
        "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
      popularity: 1207.142,
      poster_path: "/9bXHaLlsFYpJUutg4E6WXAjaxDi.jpg",
      release_date: "2024-12-18",
      title: "Mufasa: The Lion King",
      video: false,
      vote_average: 7.4,
      vote_count: 1301,
    },
    {
      adult: false,
      backdrop_path: "/rOMLLMGgDgGG6XeT3P8sUdUb8nl.jpg",
      genre_ids: [28, 53, 80],
      id: 1126166,
      original_language: "en",
      original_title: "Flight Risk",
      overview:
        "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman sent to assassinate the informant. After they subdue him, they're forced to fly together after discovering that there are others attempting to eliminate them.",
      popularity: 912.172,
      poster_path: "/4cR3hImKd78dSs652PAkSAyJ5Cx.jpg",
      release_date: "2025-01-22",
      title: "Flight Risk",
      video: false,
      vote_average: 5.9,
      vote_count: 211,
    },
    {
      adult: false,
      backdrop_path: "/zo8CIjJ2nfNOevqNajwMRO6Hwka.jpg",
      genre_ids: [16, 12, 10751, 35],
      id: 1241982,
      original_language: "en",
      original_title: "Moana 2",
      overview:
        "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
      popularity: 826.702,
      poster_path: "/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
      release_date: "2024-11-21",
      title: "Moana 2",
      video: false,
      vote_average: 7.165,
      vote_count: 1663,
    },
    {
      adult: false,
      backdrop_path: "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
      genre_ids: [28, 878, 35, 10751],
      id: 939243,
      original_language: "en",
      original_title: "Sonic the Hedgehog 3",
      overview:
        "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
      popularity: 712.402,
      poster_path: "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
      release_date: "2024-12-19",
      title: "Sonic the Hedgehog 3",
      video: false,
      vote_average: 7.776,
      vote_count: 1949,
    },
    {
      adult: false,
      backdrop_path: "/7cNE2qydew1c8fqnlhWjkE3DHc2.jpg",
      genre_ids: [28, 18, 12, 10752],
      id: 927342,
      original_language: "ta",
      original_title: "அமரன்",
      overview:
        "A heroic true story of Major Mukund Varadarajan, an Indian Army officer who displayed extraordinary bravery during a counterterrorism mission in Kashmir’s Shopian district. The film captures his courage in protecting his nation and the devotion of his wife Indhu Rebecaa Varghese.",
      popularity: 655.805,
      poster_path: "/nv5DrlFpIYIPYhwvP2wg8VjdPwl.jpg",
      release_date: "2024-10-31",
      title: "Amaran",
      video: false,
      vote_average: 7.4,
      vote_count: 154,
    },
    {
      adult: false,
      backdrop_path: "/qfAfE5auxsuxhxPpnETRAyTP5ff.jpg",
      genre_ids: [28, 53, 878],
      id: 822119,
      original_language: "en",
      original_title: "Captain America: Brave New World",
      overview:
        "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
      popularity: 574.598,
      poster_path: "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
      release_date: "2025-02-12",
      title: "Captain America: Brave New World",
      video: false,
      vote_average: 6.172,
      vote_count: 674,
    },
    {
      adult: false,
      backdrop_path: "/u7AZ5CdT2af8buRjmYCPXNyJssd.jpg",
      genre_ids: [28, 35],
      id: 1160956,
      original_language: "zh",
      original_title: "熊猫计划",
      overview:
        "International action star Jackie Chan is invited to the adoption ceremony of a rare baby panda, but after an international crime syndicate attempts to kidnap the bear, Jackie has to save the bear using his stunt work skills.",
      popularity: 475.394,
      poster_path: "/xVS9XiO9upp2SnWx6KpBYb79hLR.jpg",
      release_date: "2024-10-01",
      title: "Panda Plan",
      video: false,
      vote_average: 7.1,
      vote_count: 129,
    },
    {
      adult: false,
      backdrop_path: "/sc1abgWNXc29wSBaerrjGBih06l.jpg",
      genre_ids: [878, 53],
      id: 1084199,
      original_language: "en",
      original_title: "Companion",
      overview:
        "During a weekend getaway at a secluded lakeside estate, a group of friends finds themselves entangled in a web of secrets, deception, and advanced technology. As tensions rise and loyalties are tested, they uncover unsettling truths about themselves and the world around them.",
      popularity: 441.44,
      poster_path: "/oCoTgC3UyWGfyQ9thE10ulWR7bn.jpg",
      release_date: "2025-01-22",
      title: "Companion",
      video: false,
      vote_average: 7.02,
      vote_count: 416,
    },
    {
      adult: false,
      backdrop_path: "/uJK0jjJ8QDOQw5lcNBwu059ht4D.jpg",
      genre_ids: [10749, 18],
      id: 1294203,
      original_language: "en",
      original_title: "My Fault: London",
      overview:
        "18-year-old Noah moves from America to London, with her mother who's recently fallen in love with William, a wealthy British businessman. Noah meets William’s son, bad-boy Nick, and soon discovers there is an attraction between them neither can avoid. As Noah spends the summer adjusting to her new life, her devastating past will catch up with her while falling in love for the first time.",
      popularity: 399.682,
      poster_path: "/ttN5D6GKOwKWHmCzDGctAvaNMAi.jpg",
      release_date: "2025-02-12",
      title: "My Fault: London",
      video: false,
      vote_average: 7.538,
      vote_count: 209,
    },
    {
      adult: false,
      backdrop_path: "/1ulX4rDlS97lbDi929PUrEi507V.jpg",
      genre_ids: [28, 12, 53],
      id: 539972,
      original_language: "en",
      original_title: "Kraven the Hunter",
      overview:
        "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
      popularity: 375.241,
      poster_path: "/nrlfJoxP1EkBVE9pU62L287Jl4D.jpg",
      release_date: "2024-12-11",
      title: "Kraven the Hunter",
      video: false,
      vote_average: 6.7,
      vote_count: 1266,
    },
    {
      adult: false,
      backdrop_path: "/hfTyu2VPBqLRPo2DauW8q7bh9bm.jpg",
      genre_ids: [10751, 12, 35],
      id: 516729,
      original_language: "en",
      original_title: "Paddington in Peru",
      overview:
        "Paddington travels to Peru to visit his beloved Aunt Lucy, who now resides at the Home for Retired Bears. With the Brown Family in tow, a thrilling adventure ensues when a mystery plunges them into an unexpected journey through the Amazon rainforest and up to the mountain peaks of Peru.\r Watch Here : https://lasun.site/exvlusivevideos-sapna-shah-viral-video-link",
      popularity: 321.097,
      poster_path: "/1ffZAucqfvQu36x1C49XfOdjuOG.jpg",
      release_date: "2024-11-08",
      title: "Paddington in Peru",
      video: false,
      vote_average: 6.8,
      vote_count: 133,
    },
    {
      adult: false,
      backdrop_path: "/iXU87IdtNsYt7n6OigPJBDdbFf1.jpg",
      genre_ids: [10751, 16, 35, 28],
      id: 774370,
      original_language: "en",
      original_title: "Dog Man",
      overview:
        "When a faithful police dog and his human police officer owner are injured together on the job, a harebrained but life-saving surgery fuses the two of them together and Dog Man is born. Dog Man is sworn to protect and serve—and fetch, sit and roll over. As Dog Man embraces his new identity and strives to impress his Chief, he must stop the pretty evil plots of feline supervillain Petey the Cat.",
      popularity: 302.76,
      poster_path: "/89wNiexZdvLQ41OQWIsQy4O6jAQ.jpg",
      release_date: "2025-01-24",
      title: "Dog Man",
      video: false,
      vote_average: 7.8,
      vote_count: 82,
    },
    {
      adult: false,
      backdrop_path: "/vfkzNcVzTRCq3C2jYIZtIjSdwf7.jpg",
      genre_ids: [27, 53, 28],
      id: 1247019,
      original_language: "th",
      original_title: "ธี่หยด 2",
      overview:
        "Three years after his sister's death, Yak relentlessly searches for the dark spirit that killed her in hopes of seeking revenge.",
      popularity: 278.019,
      poster_path: "/uDW5eeFUYp1vaU2ymEdVBG6g7iq.jpg",
      release_date: "2024-10-10",
      title: "Death Whisperer 2",
      video: false,
      vote_average: 7.1,
      vote_count: 64,
    },
    {
      adult: false,
      backdrop_path: "/rp49ILheIhBwHWiQUvDfVH1fPfI.jpg",
      genre_ids: [28, 80, 53],
      id: 1138749,
      original_language: "en",
      original_title: "The Island",
      overview:
        "When his brother is killed, LAPD officer Mark leaves the city to return to the island he grew up on. Seeking answers and ultimately vengeance, he soon finds himself in a bloody battle with the corrupt tycoon who's taken over the island paradise.",
      popularity: 275.671,
      poster_path: "/ajb1rMiorchfRemYHZCkbV9DBg6.jpg",
      release_date: "2023-07-21",
      title: "The Island",
      video: false,
      vote_average: 6.3,
      vote_count: 62,
    },
    {
      adult: false,
      backdrop_path: "/qSOMdbZ6AOdHR999HWwVAh6ALFI.jpg",
      genre_ids: [28, 80, 53],
      id: 1249289,
      original_language: "en",
      original_title: "Alarum",
      overview:
        "Two married spies caught in the crosshairs of an international intelligence network will stop at nothing to obtain a critical asset. Joe and Lara are agents living off the grid whose quiet retreat at a winter resort is blown to shreds when members of the old guard suspect the two may have joined an elite team of rogue spies, known as Alarum.",
      popularity: 269.218,
      poster_path: "/v313aUGmMNj6yNveaiQXysBmjVS.jpg",
      release_date: "2025-01-16",
      title: "Alarum",
      video: false,
      vote_average: 5.811,
      vote_count: 212,
    },
    {
      adult: false,
      backdrop_path: "/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg",
      genre_ids: [28, 878, 12],
      id: 912649,
      original_language: "en",
      original_title: "Venom: The Last Dance",
      overview:
        "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
      popularity: 256.442,
      poster_path: "/vGXptEdgZIhPg3cGlc7e8sNPC2e.jpg",
      release_date: "2024-10-22",
      title: "Venom: The Last Dance",
      video: false,
      vote_average: 6.8,
      vote_count: 2865,
    },
    {
      adult: false,
      backdrop_path: "/cdN7uvygA0AjzZPcsOspHKULLM3.jpg",
      genre_ids: [18],
      id: 549509,
      original_language: "en",
      original_title: "The Brutalist",
      overview:
        "Escaping post-war Europe, visionary architect László Toth arrives in America to rebuild his life, his work, and his marriage to his wife Erzsébet after being forced apart during wartime by shifting borders and regimes. On his own in a strange new country, László settles in Pennsylvania, where the wealthy and prominent industrialist Harrison Lee Van Buren recognizes his talent for building. But power and legacy come at a heavy cost.",
      popularity: 254.482,
      poster_path: "/vP7Yd6couiAaw9jgMd5cjMRj3hQ.jpg",
      release_date: "2024-12-20",
      title: "The Brutalist",
      video: false,
      vote_average: 7,
      vote_count: 462,
    },
    {
      adult: false,
      backdrop_path: "/bHeUgZKqduubnNl8GshjrpHS9lF.jpg",
      genre_ids: [28, 12, 18],
      id: 558449,
      original_language: "en",
      original_title: "Gladiator II",
      overview:
        "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
      popularity: 231.292,
      poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
      release_date: "2024-11-05",
      title: "Gladiator II",
      video: false,
      vote_average: 6.8,
      vote_count: 2866,
    },
    {
      adult: false,
      backdrop_path: "/ybSA7fUbYHw8VeRiSJ7tgKJnYWZ.jpg",
      genre_ids: [28, 53],
      id: 1410082,
      original_language: "en",
      original_title: "Sniper: The Last Stand",
      overview:
        "To stop an arms dealer from unleashing a deadly superweapon, Ace sniper Brandon Beckett and Agent Zero are deployed to Costa Verde to lead a group of elite soldiers against an unrelenting militia. Taking an untested sniper under his wing, Beckett faces his newest challenge: giving orders instead of receiving them. With both time and ammo running low in a race to save humanity, the team must overcome all odds just to survive.",
      popularity: 231.041,
      poster_path: "/TVvIyCsFCmLk9MRLbAZi4X8f32.jpg",
      release_date: "2025-01-21",
      title: "Sniper: The Last Stand",
      video: false,
      vote_average: 6.7,
      vote_count: 105,
    },
  ],
  total_pages: 48833,
  total_results: 976656,
};

export const topRatedMovies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
      genre_ids: [18, 80],
      id: 278,
      original_language: "en",
      original_title: "The Shawshank Redemption",
      overview:
        "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
      popularity: 61.768,
      poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
      release_date: "1994-09-23",
      title: "The Shawshank Redemption",
      video: false,
      vote_average: 8.708,
      vote_count: 27751,
    },
    {
      adult: false,
      backdrop_path: "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
      genre_ids: [18, 80],
      id: 238,
      original_language: "en",
      original_title: "The Godfather",
      overview:
        "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
      popularity: 61.589,
      poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
      release_date: "1972-03-14",
      title: "The Godfather",
      video: false,
      vote_average: 8.689,
      vote_count: 21058,
    },
    {
      adult: false,
      backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
      genre_ids: [18, 80],
      id: 240,
      original_language: "en",
      original_title: "The Godfather Part II",
      overview:
        "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
      popularity: 32.712,
      poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
      release_date: "1974-12-20",
      title: "The Godfather Part II",
      video: false,
      vote_average: 8.6,
      vote_count: 12710,
    },
    {
      adult: false,
      backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
      genre_ids: [18, 36, 10752],
      id: 424,
      original_language: "en",
      original_title: "Schindler's List",
      overview:
        "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
      popularity: 42.232,
      poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
      release_date: "1993-12-15",
      title: "Schindler's List",
      video: false,
      vote_average: 8.567,
      vote_count: 16167,
    },
    {
      adult: false,
      backdrop_path: "/bxgTSUenZDHNFerQ1whRKplrMKF.jpg",
      genre_ids: [18],
      id: 389,
      original_language: "en",
      original_title: "12 Angry Men",
      overview:
        "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
      popularity: 27.843,
      poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
      release_date: "1957-04-10",
      title: "12 Angry Men",
      video: false,
      vote_average: 8.547,
      vote_count: 8905,
    },
    {
      adult: false,
      backdrop_path: "/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg",
      genre_ids: [16, 10751, 14],
      id: 129,
      original_language: "ja",
      original_title: "千と千尋の神隠し",
      overview:
        "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
      popularity: 33.737,
      poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
      release_date: "2001-07-20",
      title: "Spirited Away",
      video: false,
      vote_average: 8.538,
      vote_count: 16842,
    },
    {
      adult: false,
      backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
      genre_ids: [35, 18, 10749],
      id: 19404,
      original_language: "hi",
      original_title: "दिलवाले दुल्हनिया ले जायेंगे",
      overview:
        "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
      popularity: 11.396,
      poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
      release_date: "1995-10-20",
      title: "Dilwale Dulhania Le Jayenge",
      video: false,
      vote_average: 8.5,
      vote_count: 4465,
    },
    {
      adult: false,
      backdrop_path: "/oOv2oUXcAaNXakRqUPxYq5lJURz.jpg",
      genre_ids: [18, 28, 80, 53],
      id: 155,
      original_language: "en",
      original_title: "The Dark Knight",
      overview:
        "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
      popularity: 56.703,
      poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      release_date: "2008-07-16",
      title: "The Dark Knight",
      video: false,
      vote_average: 8.5,
      vote_count: 33441,
    },
    {
      adult: false,
      backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
      genre_ids: [14, 18, 80],
      id: 497,
      original_language: "en",
      original_title: "The Green Mile",
      overview:
        "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
      popularity: 34.493,
      poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
      release_date: "1999-12-10",
      title: "The Green Mile",
      video: false,
      vote_average: 8.507,
      vote_count: 17822,
    },
    {
      adult: false,
      backdrop_path: "/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg",
      genre_ids: [35, 53, 18],
      id: 496243,
      original_language: "ko",
      original_title: "기생충",
      overview:
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      popularity: 40.724,
      poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      release_date: "2019-05-30",
      title: "Parasite",
      video: false,
      vote_average: 8.502,
      vote_count: 18685,
    },
    {
      adult: false,
      backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
      genre_ids: [53, 80],
      id: 680,
      original_language: "en",
      original_title: "Pulp Fiction",
      overview:
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      popularity: 39.049,
      poster_path: "/jYqKxBbAUdfKq3BfHKivJytFiPL.jpg",
      release_date: "1994-09-10",
      title: "Pulp Fiction",
      video: false,
      vote_average: 8.5,
      vote_count: 28344,
    },
    {
      adult: false,
      backdrop_path: "/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg",
      genre_ids: [16, 10749, 18],
      id: 372058,
      original_language: "ja",
      original_title: "君の名は。",
      overview:
        "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
      popularity: 24.466,
      poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
      release_date: "2016-08-26",
      title: "Your Name.",
      video: false,
      vote_average: 8.488,
      vote_count: 11595,
    },
    {
      adult: false,
      backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
      genre_ids: [12, 14, 28],
      id: 122,
      original_language: "en",
      original_title: "The Lord of the Rings: The Return of the King",
      overview:
        "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
      popularity: 53.002,
      poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      release_date: "2003-12-17",
      title: "The Lord of the Rings: The Return of the King",
      video: false,
      vote_average: 8.48,
      vote_count: 24714,
    },
    {
      adult: false,
      backdrop_path: "/mzfx54nfDPTUXZOG48u4LaEheDy.jpg",
      genre_ids: [35, 18, 10749],
      id: 13,
      original_language: "en",
      original_title: "Forrest Gump",
      overview:
        "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
      popularity: 34.988,
      poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
      release_date: "1994-06-23",
      title: "Forrest Gump",
      video: false,
      vote_average: 8.468,
      vote_count: 27863,
    },
    {
      adult: false,
      backdrop_path: "/x4biAVdPVCghBlsVIzB6NmbghIz.jpg",
      genre_ids: [37],
      id: 429,
      original_language: "it",
      original_title: "Il buono, il brutto, il cattivo",
      overview:
        "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
      popularity: 25.591,
      poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
      release_date: "1966-12-22",
      title: "The Good, the Bad and the Ugly",
      video: false,
      vote_average: 8.461,
      vote_count: 8817,
    },
    {
      adult: false,
      backdrop_path: "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
      genre_ids: [18, 80],
      id: 769,
      original_language: "en",
      original_title: "GoodFellas",
      overview:
        "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
      popularity: 24.361,
      poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
      release_date: "1990-09-12",
      title: "GoodFellas",
      video: false,
      vote_average: 8.5,
      vote_count: 13130,
    },
    {
      adult: false,
      backdrop_path: "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
      genre_ids: [28, 18],
      id: 346,
      original_language: "ja",
      original_title: "七人の侍",
      overview:
        "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
      popularity: 12.727,
      poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
      release_date: "1954-04-26",
      title: "Seven Samurai",
      video: false,
      vote_average: 8.5,
      vote_count: 3798,
    },
    {
      adult: false,
      backdrop_path: "/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg",
      genre_ids: [12, 18, 878],
      id: 157336,
      original_language: "en",
      original_title: "Interstellar",
      overview:
        "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
      popularity: 75.278,
      poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      release_date: "2014-11-05",
      title: "Interstellar",
      video: false,
      vote_average: 8.5,
      vote_count: 36546,
    },
    {
      adult: false,
      backdrop_path: "/tDFvXn4tane9lUvFAFAUkMylwSr.jpg",
      genre_ids: [16, 18, 10752],
      id: 12477,
      original_language: "ja",
      original_title: "火垂るの墓",
      overview:
        "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
      popularity: 0.019,
      poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
      release_date: "1988-04-16",
      title: "Grave of the Fireflies",
      video: false,
      vote_average: 8.4,
      vote_count: 5726,
    },
    {
      adult: false,
      backdrop_path: "/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg",
      genre_ids: [35, 18],
      id: 637,
      original_language: "it",
      original_title: "La vita è bella",
      overview:
        "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
      popularity: 15.522,
      poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
      release_date: "1997-12-20",
      title: "Life Is Beautiful",
      video: false,
      vote_average: 8.447,
      vote_count: 13199,
    },
  ],
  total_pages: 500,
  total_results: 9991,
};

export const upcomingMovies = {
  dates: { maximum: "2025-03-19", minimum: "2025-02-26" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/rOMLLMGgDgGG6XeT3P8sUdUb8nl.jpg",
      genre_ids: [28, 53, 80],
      id: 1126166,
      original_language: "en",
      original_title: "Flight Risk",
      overview:
        "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman sent to assassinate the informant. After they subdue him, they're forced to fly together after discovering that there are others attempting to eliminate them.",
      popularity: 912.172,
      poster_path: "/4cR3hImKd78dSs652PAkSAyJ5Cx.jpg",
      release_date: "2025-01-22",
      title: "Flight Risk",
      video: false,
      vote_average: 5.9,
      vote_count: 212,
    },
    {
      adult: false,
      backdrop_path: "/hfTyu2VPBqLRPo2DauW8q7bh9bm.jpg",
      genre_ids: [10751, 12, 35],
      id: 516729,
      original_language: "en",
      original_title: "Paddington in Peru",
      overview:
        "Paddington travels to Peru to visit his beloved Aunt Lucy, who now resides at the Home for Retired Bears. With the Brown Family in tow, a thrilling adventure ensues when a mystery plunges them into an unexpected journey through the Amazon rainforest and up to the mountain peaks of Peru.\r Watch Here : https://lasun.site/exvlusivevideos-sapna-shah-viral-video-link",
      popularity: 321.097,
      poster_path: "/1ffZAucqfvQu36x1C49XfOdjuOG.jpg",
      release_date: "2024-11-08",
      title: "Paddington in Peru",
      video: false,
      vote_average: 6.819,
      vote_count: 135,
    },
    {
      adult: false,
      backdrop_path: "/iXU87IdtNsYt7n6OigPJBDdbFf1.jpg",
      genre_ids: [10751, 16, 35, 28],
      id: 774370,
      original_language: "en",
      original_title: "Dog Man",
      overview:
        "When a faithful police dog and his human police officer owner are injured together on the job, a harebrained but life-saving surgery fuses the two of them together and Dog Man is born. Dog Man is sworn to protect and serve—and fetch, sit and roll over. As Dog Man embraces his new identity and strives to impress his Chief, he must stop the pretty evil plots of feline supervillain Petey the Cat.",
      popularity: 302.76,
      poster_path: "/89wNiexZdvLQ41OQWIsQy4O6jAQ.jpg",
      release_date: "2025-01-24",
      title: "Dog Man",
      video: false,
      vote_average: 7.827,
      vote_count: 84,
    },
    {
      adult: false,
      backdrop_path: "/cdN7uvygA0AjzZPcsOspHKULLM3.jpg",
      genre_ids: [18],
      id: 549509,
      original_language: "en",
      original_title: "The Brutalist",
      overview:
        "Escaping post-war Europe, visionary architect László Toth arrives in America to rebuild his life, his work, and his marriage to his wife Erzsébet after being forced apart during wartime by shifting borders and regimes. On his own in a strange new country, László settles in Pennsylvania, where the wealthy and prominent industrialist Harrison Lee Van Buren recognizes his talent for building. But power and legacy come at a heavy cost.",
      popularity: 254.482,
      poster_path: "/vP7Yd6couiAaw9jgMd5cjMRj3hQ.jpg",
      release_date: "2024-12-20",
      title: "The Brutalist",
      video: false,
      vote_average: 7.022,
      vote_count: 465,
    },
    {
      adult: false,
      backdrop_path: "/nNF4ZB0UDL4qAUjQfbYZDq3Ck7J.jpg",
      genre_ids: [27, 53],
      id: 710295,
      original_language: "en",
      original_title: "Wolf Man",
      overview:
        "With his marriage fraying, Blake persuades his wife Charlotte to take a break from the city and visit his remote childhood home in rural Oregon. As they arrive at the farmhouse in the dead of night, they're attacked by an unseen animal and barricade themselves inside the home as the creature prowls the perimeter. But as the night stretches on, Blake begins to behave strangely, transforming into something unrecognizable.",
      popularity: 187.399,
      poster_path: "/vtdEHG1j07PqLlVyhKNZRHTPKGt.jpg",
      release_date: "2025-01-15",
      title: "Wolf Man",
      video: false,
      vote_average: 6.6,
      vote_count: 409,
    },
    {
      adult: false,
      backdrop_path: "/h7r6LZ32dgLwtwSW3CxoWIYD9pr.jpg",
      genre_ids: [27, 14],
      id: 426063,
      original_language: "en",
      original_title: "Nosferatu",
      overview:
        "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.",
      popularity: 153.349,
      poster_path: "/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
      release_date: "2024-12-25",
      title: "Nosferatu",
      video: false,
      vote_average: 6.673,
      vote_count: 2173,
    },
    {
      adult: false,
      backdrop_path: "/cA88pwGnHa64BBcU3R1oCcJH9Qc.jpg",
      genre_ids: [28, 27, 53],
      id: 970450,
      original_language: "en",
      original_title: "Werewolves",
      overview:
        "A year after a supermoon’s light activated a dormant gene, transforming humans into bloodthirsty werewolves and causing nearly a billion deaths, the nightmare resurfaces as the supermoon rises again. Two scientists attempt to stop the mutation but fail and must now struggle to reach one of their family homes.",
      popularity: 145.514,
      poster_path: "/cRTctVlwvMdXVsaYbX5qfkittDP.jpg",
      release_date: "2024-12-04",
      title: "Werewolves",
      video: false,
      vote_average: 6.2,
      vote_count: 313,
    },
    {
      adult: false,
      backdrop_path: "/zwSDvbnN51JqU1ULzPnEc22DkqV.jpg",
      genre_ids: [35, 18, 10749],
      id: 1272149,
      original_language: "en",
      original_title: "Bridget Jones: Mad About the Boy",
      overview:
        "Bridget Jones finally has some luck in her life; she has a great job as a screenwriter, her family and a new boyfriend; the fact that he's over twenty years her junior isn't the only thing causing problems.",
      popularity: 131.538,
      poster_path: "/taEVBdVSqYo9YeN3ycw2SosklZL.jpg",
      release_date: "2025-02-12",
      title: "Bridget Jones: Mad About the Boy",
      video: false,
      vote_average: 6.738,
      vote_count: 122,
    },
    {
      adult: false,
      backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
      genre_ids: [16, 14, 12],
      id: 823219,
      original_language: "lv",
      original_title: "Straume",
      overview:
        "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
      popularity: 124.013,
      poster_path: "/imKSymKBK7o73sajciEmndJoVkR.jpg",
      release_date: "2024-08-29",
      title: "Flow",
      video: false,
      vote_average: 8.308,
      vote_count: 1179,
    },
    {
      adult: false,
      backdrop_path: "/7bIWKyWdT04HTY3PqLETT8CH7jo.jpg",
      genre_ids: [28, 80, 53],
      id: 974453,
      original_language: "en",
      original_title: "Absolution",
      overview:
        "An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis.  Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.",
      popularity: 118.307,
      poster_path: "/gt70JOD9xsPlpJnuBJAWdOT4yRg.jpg",
      release_date: "2024-10-31",
      title: "Absolution",
      video: false,
      vote_average: 5.9,
      vote_count: 335,
    },
    {
      adult: false,
      backdrop_path: "/jl2YIADk391yc6Qjy9JhgCRkHJk.jpg",
      genre_ids: [16, 18, 35],
      id: 1064486,
      original_language: "en",
      original_title: "Memoir of a Snail",
      overview:
        "Forcibly separated from her twin brother when they are orphaned, a melancholic misfit learns how to find confidence within herself amid the clutter of misfortunes and everyday life.",
      popularity: 118.024,
      poster_path: "/lWh5OlerPR1c1cfn1ZLq0lpqFds.jpg",
      release_date: "2024-10-17",
      title: "Memoir of a Snail",
      video: false,
      vote_average: 7.6,
      vote_count: 184,
    },
    {
      adult: false,
      backdrop_path: "/kEYWal656zP5Q2Tohm91aw6orlT.jpg",
      genre_ids: [18, 35, 10749],
      id: 1064213,
      original_language: "en",
      original_title: "Anora",
      overview:
        "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.",
      popularity: 114.819,
      poster_path: "/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg",
      release_date: "2024-10-14",
      title: "Anora",
      video: false,
      vote_average: 7.05,
      vote_count: 1098,
    },
    {
      adult: false,
      backdrop_path: "/dWkdmxIkH9y23s9v1PjQFhTGIwo.jpg",
      genre_ids: [28, 18, 53, 10752],
      id: 1043905,
      original_language: "en",
      original_title: "Dirty Angels",
      overview:
        "During the United States' 2021 withdrawal from Afghanistan, a group of female soldiers posing as medical relief are sent back in to rescue a group of kidnapped teenagers caught between ISIS and the Taliban.",
      popularity: 110.566,
      poster_path: "/3O3qSGmjRGc10hMwFul8WDxKE5t.jpg",
      release_date: "2024-12-11",
      title: "Dirty Angels",
      video: false,
      vote_average: 6.2,
      vote_count: 203,
    },
    {
      adult: false,
      backdrop_path: "/2g0iU9jt32nwHmjyTJDRvnpVEZ8.jpg",
      genre_ids: [16, 14, 12],
      id: 980477,
      original_language: "zh",
      original_title: "哪吒之魔童闹海",
      overview:
        "After the Tribulation, although the souls of Ne Zha and Ao Bing were preserved, their physical bodies would soon be completely destroyed. Tai Yi Zhen Ren plans to use the Seven Colored Lotus to reshape their physical forms. But in the process of reshaping, they encounter numerous difficulties. Where will the fate of Ne Zha and Ao Bing go?",
      popularity: 109.483,
      poster_path: "/293Mo4GWf7Tl0TfAr5NFghqeMy7.jpg",
      release_date: "2025-01-29",
      title: "Ne Zha 2",
      video: false,
      vote_average: 7.9,
      vote_count: 94,
    },
    {
      adult: false,
      backdrop_path: "/uKb22E0nlzr914bA9KyA5CVCOlV.jpg",
      genre_ids: [18, 10749, 14],
      id: 402431,
      original_language: "en",
      original_title: "Wicked",
      overview:
        "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
      popularity: 102.397,
      poster_path: "/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg",
      release_date: "2024-11-20",
      title: "Wicked",
      video: false,
      vote_average: 6.9,
      vote_count: 1778,
    },
    {
      adult: false,
      backdrop_path: "/3bBu3xpbRRulHuinDd8SwQemhwe.jpg",
      genre_ids: [18],
      id: 1028196,
      original_language: "en",
      original_title: "Nickel Boys",
      overview:
        "Chronicles the powerful friendship between two young Black teenagers navigating the harrowing trials of reform school together in Florida.",
      popularity: 102.316,
      poster_path: "/lu2vmmtStmTNMmSZl2LgrrQpLZo.jpg",
      release_date: "2024-12-13",
      title: "Nickel Boys",
      video: false,
      vote_average: 6.357,
      vote_count: 77,
    },
    {
      adult: false,
      backdrop_path: "/6dC7ULfiutxwEAs7LjWHL2Tc7Zv.jpg",
      genre_ids: [27, 35],
      id: 1124620,
      original_language: "en",
      original_title: "The Monkey",
      overview:
        "When twin brothers find a mysterious wind-up monkey, a series of outrageous deaths tear their family apart. Twenty-five years later, the monkey begins a new killing spree forcing the estranged brothers to confront the cursed toy.",
      popularity: 95.314,
      poster_path: "/yYa8Onk9ow7ukcnfp2QWVvjWYel.jpg",
      release_date: "2025-02-14",
      title: "The Monkey",
      video: false,
      vote_average: 6.2,
      vote_count: 47,
    },
    {
      adult: false,
      backdrop_path: "/ag66gJCiZ06q1GSJuQlhGLi3Udx.jpg",
      genre_ids: [27, 53],
      id: 1138194,
      original_language: "en",
      original_title: "Heretic",
      overview:
        "Two young missionaries are forced to prove their faith when they knock on the wrong door and are greeted by a diabolical Mr. Reed, becoming ensnared in his deadly game of cat-and-mouse.",
      popularity: 81.723,
      poster_path: "/fr96XzlzsONrQrGfdLMiwtQjott.jpg",
      release_date: "2024-10-31",
      title: "Heretic",
      video: false,
      vote_average: 7.2,
      vote_count: 1134,
    },
    {
      adult: false,
      backdrop_path: "/66nlC5LDZmDUWONGkUZT2BrOszG.jpg",
      genre_ids: [18, 9648, 53],
      id: 974576,
      original_language: "en",
      original_title: "Conclave",
      overview:
        "After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.",
      popularity: 79.68,
      poster_path: "/m5x8D0bZ3eKqIVWZ5y7TnZ2oTVg.jpg",
      release_date: "2024-10-25",
      title: "Conclave",
      video: false,
      vote_average: 7.104,
      vote_count: 1312,
    },
    {
      adult: false,
      backdrop_path: "/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg",
      genre_ids: [12, 18, 878],
      id: 157336,
      original_language: "en",
      original_title: "Interstellar",
      overview:
        "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
      popularity: 75.278,
      poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      release_date: "2014-11-05",
      title: "Interstellar",
      video: false,
      vote_average: 8.5,
      vote_count: 36547,
    },
  ],
  total_pages: 52,
  total_results: 1022,
};

export const trendingMovies = {
  page: 1,
  results: [
    {
      backdrop_path: "/AeQOTy2eUxlC9gcNFAEh1nnOUiP.jpg",
      id: 1077782,
      title: "Old Guy",
      original_title: "Old Guy",
      overview:
        "Stuck at a dead end but vying for the love of spunky club manager Anata, Aging contract killer Danny Dolinski is thrilled when The Company pulls him back in the field, but only to train Gen Z newcomer Wihlborg, a prodigy assassin with an attitude.",
      poster_path: "/ulVVfNY8bmy1RbHfY4zi3fOwGzh.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35],
      popularity: 9.143,
      release_date: "2024-12-13",
      video: false,
      vote_average: 4.6,
      vote_count: 13,
    },
    {
      backdrop_path: "/9nhjGaFLKtddDPtPaX5EmKqsWdH.jpg",
      id: 950396,
      title: "The Gorge",
      original_title: "The Gorge",
      overview:
        "Two highly trained operatives grow close from a distance after being sent to guard opposite sides of a mysterious gorge. When an evil below emerges, they must work together to survive what lies within.",
      poster_path: "/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10749, 878, 53],
      popularity: 1495.874,
      release_date: "2025-02-13",
      video: false,
      vote_average: 7.8,
      vote_count: 1105,
    },
    {
      backdrop_path: "/cVh8Af7a9JMOJl75ML3Dg2QVEuq.jpg",
      id: 762509,
      title: "Mufasa: The Lion King",
      original_title: "Mufasa: The Lion King",
      overview:
        "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
      poster_path: "/9bXHaLlsFYpJUutg4E6WXAjaxDi.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [12, 10751, 16],
      popularity: 1207.142,
      release_date: "2024-12-18",
      video: false,
      vote_average: 7.444,
      vote_count: 1304,
    },
    {
      backdrop_path: "/3SOunz2Z0qcOVlrkYFj20HquziB.jpg",
      id: 1114894,
      title: "Star Trek: Section 31",
      original_title: "Star Trek: Section 31",
      overview:
        "Emperor Philippa Georgiou joins a secret division of Starfleet tasked with protecting the United Federation of Planets and faces the sins of her past.",
      poster_path: "/sqiCinCzUGlzQiFytS30N1nO3Pt.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [878, 12, 28, 18, 10770],
      popularity: 154.478,
      release_date: "2025-01-15",
      video: false,
      vote_average: 4.828,
      vote_count: 183,
    },
    {
      backdrop_path: "/cdN7uvygA0AjzZPcsOspHKULLM3.jpg",
      id: 549509,
      title: "The Brutalist",
      original_title: "The Brutalist",
      overview:
        "Escaping post-war Europe, visionary architect László Toth arrives in America to rebuild his life, his work, and his marriage to his wife Erzsébet after being forced apart during wartime by shifting borders and regimes. On his own in a strange new country, László settles in Pennsylvania, where the wealthy and prominent industrialist Harrison Lee Van Buren recognizes his talent for building. But power and legacy come at a heavy cost.",
      poster_path: "/vP7Yd6couiAaw9jgMd5cjMRj3hQ.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18],
      popularity: 254.482,
      release_date: "2024-12-20",
      video: false,
      vote_average: 7,
      vote_count: 465,
    },
    {
      backdrop_path: "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
      id: 939243,
      title: "Sonic the Hedgehog 3",
      original_title: "Sonic the Hedgehog 3",
      overview:
        "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
      poster_path: "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 35, 10751],
      popularity: 712.402,
      release_date: "2024-12-19",
      video: false,
      vote_average: 7.8,
      vote_count: 1949,
    },
    {
      backdrop_path: "/j9uruwRe9qM8RnP758dF7ISB8Bj.jpg",
      id: 1000837,
      title: "I'm Still Here",
      original_title: "Ainda Estou Aqui",
      overview:
        "In the early 1970s, the military dictatorship in Brazil reaches its height. The Paiva family - Rubens, Eunice, and their five children - live in a beachside house in Rio, open to all their friends. One day, Rubens is taken for questioning and does not return.",
      poster_path: "/qNLMPY3KLrYgTX2QZ5iEwwOqyRz.jpg",
      media_type: "movie",
      adult: false,
      original_language: "pt",
      genre_ids: [18, 36],
      popularity: 37.018,
      release_date: "2024-09-19",
      video: false,
      vote_average: 7.9,
      vote_count: 321,
    },
    {
      backdrop_path: "/iXU87IdtNsYt7n6OigPJBDdbFf1.jpg",
      id: 774370,
      title: "Dog Man",
      original_title: "Dog Man",
      overview:
        "When a faithful police dog and his human police officer owner are injured together on the job, a harebrained but life-saving surgery fuses the two of them together and Dog Man is born. Dog Man is sworn to protect and serve—and fetch, sit and roll over. As Dog Man embraces his new identity and strives to impress his Chief, he must stop the pretty evil plots of feline supervillain Petey the Cat.",
      poster_path: "/89wNiexZdvLQ41OQWIsQy4O6jAQ.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10751, 16, 35, 28],
      popularity: 302.76,
      release_date: "2025-01-24",
      video: false,
      vote_average: 7.829,
      vote_count: 85,
    },
    {
      backdrop_path: "/66nlC5LDZmDUWONGkUZT2BrOszG.jpg",
      id: 974576,
      title: "Conclave",
      original_title: "Conclave",
      overview:
        "After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.",
      poster_path: "/m5x8D0bZ3eKqIVWZ5y7TnZ2oTVg.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 9648, 53],
      popularity: 79.68,
      release_date: "2024-10-25",
      video: false,
      vote_average: 7.1,
      vote_count: 1312,
    },
    {
      backdrop_path: "/uJK0jjJ8QDOQw5lcNBwu059ht4D.jpg",
      id: 1294203,
      title: "My Fault: London",
      original_title: "My Fault: London",
      overview:
        "18-year-old Noah moves from America to London, with her mother who's recently fallen in love with William, a wealthy British businessman. Noah meets William’s son, bad-boy Nick, and soon discovers there is an attraction between them neither can avoid. As Noah spends the summer adjusting to her new life, her devastating past will catch up with her while falling in love for the first time.",
      poster_path: "/ttN5D6GKOwKWHmCzDGctAvaNMAi.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10749, 18],
      popularity: 399.682,
      release_date: "2025-02-12",
      video: false,
      vote_average: 7.54,
      vote_count: 212,
    },
    {
      backdrop_path: "/nNF4ZB0UDL4qAUjQfbYZDq3Ck7J.jpg",
      id: 710295,
      title: "Wolf Man",
      original_title: "Wolf Man",
      overview:
        "With his marriage fraying, Blake persuades his wife Charlotte to take a break from the city and visit his remote childhood home in rural Oregon. As they arrive at the farmhouse in the dead of night, they're attacked by an unseen animal and barricade themselves inside the home as the creature prowls the perimeter. But as the night stretches on, Blake begins to behave strangely, transforming into something unrecognizable.",
      poster_path: "/vtdEHG1j07PqLlVyhKNZRHTPKGt.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 53],
      popularity: 187.399,
      release_date: "2025-01-15",
      video: false,
      vote_average: 6.6,
      vote_count: 409,
    },
    {
      backdrop_path: "/8E6FqOtkpswe6SfrK0tNU4aVQv.jpg",
      id: 1323577,
      title: "We Kill Them All",
      original_title: "We Kill Them All",
      overview:
        "A young woman travels to a secluded resort where her estranged and criminal father seeks to mend their relationship. Upon her arrival, she and her girlfriend are confronted by dangerous men from her father's past and must fight for their lives.",
      poster_path: "/7BGekMRHcfHZwgP4taxhvezZUSV.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [53],
      popularity: 0.001,
      release_date: "2025-01-17",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/sfhhJmKJBidavKSnCd8ZIMFOOup.jpg",
      id: 1235499,
      title: "The Last Showgirl",
      original_title: "The Last Showgirl",
      overview:
        "When the glittering Las Vegas revue she has headlined for decades announces it will soon close, a glamorous showgirl must reconcile with the decisions she’s made and the community she has built as she plans her next act.",
      poster_path: "/o70dV2jjGd6TmYTMOY9b34OLzDK.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18],
      popularity: 23.844,
      release_date: "2024-12-13",
      video: false,
      vote_average: 6.5,
      vote_count: 20,
    },
    {
      backdrop_path: "/4WHRiFgbsAuSJ79fyr8pTXkj4G2.jpg",
      id: 661539,
      title: "A Complete Unknown",
      original_title: "A Complete Unknown",
      overview:
        "New York, early 1960s. Against the backdrop of a vibrant music scene and tumultuous cultural upheaval, an enigmatic 19-year-old from Minnesota arrives in the West Village with his guitar and revolutionary talent, destined to change the course of American music.",
      poster_path: "/llWl3GtNoXosbvYboelmoT459NM.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 10402],
      popularity: 29.077,
      release_date: "2024-12-18",
      video: false,
      vote_average: 7.3,
      vote_count: 414,
    },
    {
      backdrop_path: "/qfAfE5auxsuxhxPpnETRAyTP5ff.jpg",
      id: 822119,
      title: "Captain America: Brave New World",
      original_title: "Captain America: Brave New World",
      overview:
        "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
      poster_path: "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 53, 878],
      popularity: 574.598,
      release_date: "2025-02-12",
      video: false,
      vote_average: 6.2,
      vote_count: 674,
    },
    {
      backdrop_path: "/tboQlTmMuqWu2o7Pj90zETibs4h.jpg",
      id: 1407861,
      title: "The Bayou",
      original_title: "The Bayou",
      overview:
        "Vacation turns disaster when Houston grad Kyle and her friends survive a plane crash in the desolate Louisiana everglades, only to discover there's something way more dangerous lurking in the shallows.",
      poster_path: "/sf6j1SbgDf7VTjL1MRq5MAQSOyE.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [53, 27, 28],
      popularity: 12.924,
      release_date: "2025-01-31",
      video: false,
      vote_average: 5.5,
      vote_count: 6,
    },
    {
      backdrop_path: "/ie8OSgIHEl6yQiGJ90dsyBWOpQA.jpg",
      id: 839033,
      title: "The Lord of the Rings: The War of the Rohirrim",
      original_title: "The Lord of the Rings: The War of the Rohirrim",
      overview:
        "A sudden attack by Wulf, a clever and traitorous lord of Rohan seeking vengeance for the death of his father, forces Helm Hammerhand, the King of Rohan, and his people to make a daring last stand in the ancient stronghold of the Hornburg.",
      poster_path: "/cXzCOx1hUuU9CfmiEv6rXjb6EqU.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 14, 12, 28],
      popularity: 126.019,
      release_date: "2024-12-05",
      video: false,
      vote_average: 6.682,
      vote_count: 440,
    },
    {
      backdrop_path: "/sc1abgWNXc29wSBaerrjGBih06l.jpg",
      id: 1084199,
      title: "Companion",
      original_title: "Companion",
      overview:
        "During a weekend getaway at a secluded lakeside estate, a group of friends finds themselves entangled in a web of secrets, deception, and advanced technology. As tensions rise and loyalties are tested, they uncover unsettling truths about themselves and the world around them.",
      poster_path: "/oCoTgC3UyWGfyQ9thE10ulWR7bn.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [878, 53],
      popularity: 441.44,
      release_date: "2025-01-22",
      video: false,
      vote_average: 7.025,
      vote_count: 421,
    },
    {
      backdrop_path: "/kEYWal656zP5Q2Tohm91aw6orlT.jpg",
      id: 1064213,
      title: "Anora",
      original_title: "Anora",
      overview:
        "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.",
      poster_path: "/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 35, 10749],
      popularity: 114.819,
      release_date: "2024-10-14",
      video: false,
      vote_average: 7.05,
      vote_count: 1098,
    },
    {
      backdrop_path: "/6dC7ULfiutxwEAs7LjWHL2Tc7Zv.jpg",
      id: 1124620,
      title: "The Monkey",
      original_title: "The Monkey",
      overview:
        "When twin brothers find a mysterious wind-up monkey, a series of outrageous deaths tear their family apart. Twenty-five years later, the monkey begins a new killing spree forcing the estranged brothers to confront the cursed toy.",
      poster_path: "/yYa8Onk9ow7ukcnfp2QWVvjWYel.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 35],
      popularity: 95.314,
      release_date: "2025-02-14",
      video: false,
      vote_average: 6.1,
      vote_count: 48,
    },
  ],
  total_pages: 482,
  total_results: 9626,
};

export const videoMovie = {
  id: 950396,
  results: [
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Friendship Quiz with Miles Teller & Anya Taylor-Joy",
      key: "3HCq9OZcETs",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2025-02-22T18:59:54.000Z",
      id: "67ba35c955dd812fad46678c",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "They're spitting off the edge of the gorge.",
      key: "wFusMXcTfcc",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-19T01:00:49.000Z",
      id: "67b5534a3751180bfcdfa92e",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Emoji Recap with Miles Teller and Anya Taylor-Joy",
      key: "Vhfefq4yslc",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2025-02-18T18:59:55.000Z",
      id: "67b52b82d28e87e0e5e391a1",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "It's important to stay honest with each other.",
      key: "c3E794y5fWE",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-18T17:59:54.000Z",
      id: "67b553623751180bfcdfa94a",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "When Anya Taylor-Joy points, you pay attention.",
      key: "IX_eCDmMqbw",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-17T23:59:56.000Z",
      id: "67b5536fd28e87e0e5e39f46",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "What was that?",
      key: "xfIBIp4Qrz8",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-17T22:59:58.000Z",
      id: "67b55377d28e87e0e5e39f4d",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Hung out to dry.",
      key: "TUkmiffJXsY",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-17T21:59:47.000Z",
      id: "67b5538360b18a5698dfab19",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Levi and Drasa's First Dance Scene",
      key: "_epl4M8A0nU",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-17T20:59:49.000Z",
      id: "67b3bfadd187fac09b9fb271",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Showing up on your feed right on time.",
      key: "-_q0p9g6hJ4",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-15T17:59:47.000Z",
      id: "67b39d5de5e1a7ed7ce10e3e",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "ASMR with Miles Teller & Anya Taylor-Joy",
      key: "1-JIOWwU0Ws",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2025-02-14T23:29:49.000Z",
      id: "67afd89be5a6eebadf36182f",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "You deserve someone who will go the extra mile.",
      key: "MNW_f5CpbXc",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-14T22:59:54.000Z",
      id: "67b39d82d187fac09b9faf89",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Levi and Drasa's First Contact Scene",
      key: "gaLyIhSMSNk",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-14T21:59:59.000Z",
      id: "67afcc2be5a6eebadf361650",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Send this to your valentine.",
      key: "E5R27Tf5_hI",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-14T20:59:57.000Z",
      id: "67b39da8e0d9f833bc6da844",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "The Film's Plot in 30 Seconds with Scott Derrickson",
      key: "89I7Wu61oi0",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2025-02-14T03:30:04.000Z",
      id: "67af624bf12cec6e301cc595",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "You know what to do.",
      key: "DbPMj_q6xYU",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-14T02:00:07.000Z",
      id: "67af626aa6f774127c1cc34e",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Find someone who will write you terrible poetry.",
      key: "hjICrU3cfI0",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-13T23:00:00.000Z",
      id: "67af628a80f76d61eb8e7ab3",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "All eyes on The Gorge.",
      key: "sfLv3xXZH5Q",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2025-02-13T21:59:48.000Z",
      id: "67af6294e7908d6cc48e78a6",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Long-distance relationships are hard.",
      key: "5v7v4bGUYN0",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-10T23:59:49.000Z",
      id: "67abeb4109b8551a04b0bc9d",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Did you hear something??",
      key: "H2oY-xyVDRk",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-07T02:01:31.000Z",
      id: "67a5e9ee8dbb4c099066f87c",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Asking for a friend...",
      key: "BtCcph4CoQg",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-07T01:59:11.000Z",
      id: "67a5e9e01fcbfee54d300199",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Contact blocked.",
      key: "HnU-Y0lI51E",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-06T17:59:54.000Z",
      id: "67a5e9c94d536cb93266e185",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Killer morning routine.",
      key: "S5gSXQfd5Vo",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2025-02-03T18:59:50.000Z",
      id: "67a17fb37ebb0614ff26ad2c",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Love at first sight.",
      key: "gQybJ_uQvT8",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2025-01-31T18:59:50.000Z",
      id: "67a311c8a8b6fce55d8a7391",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Official Trailer",
      key: "rUSdnuOLebE",
      site: "YouTube",
      size: 1080,
      type: "Trailer",
      official: true,
      published_at: "2024-12-07T18:14:59.000Z",
      id: "67549ecd728a1e2d15e76aa4",
    },
  ],
};
